name: Deploy to PyPI

on:
  create

jobs:
  deploy:
    if: startsWith(github.ref, 'refs/tags/')

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        source ci/ci_ubuntu.sh
        deployment_dependencies

    - name: Build Package
      run: |
        source ci/ci_ubuntu.sh
        build

    - name: Create artifacts
      uses: actions/upload-artifact@v1
      with:
        name: plyer_artifact
        path: dist

    - name: Upload to GitHub Releases
      uses: softprops/action-gh-release@v0.1.14
      with:
        files: dist/*
        draft: true

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

      run: |
        source ci/ci_ubuntu.sh
        deploy
