name: 'Support Requests'

on:
  issues:
    types: [labeled, unlabeled, reopened]

permissions:
  issues: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/support-requests@v4
        with:
          github-token: ${{ github.token }}
          support-label: 'support'
          issue-comment: >
            👋 We use the issue tracker exclusively for bug reports and feature requests.
            However, this issue appears to be a support request. Please use our
            [support channels](https://github.com/kivy/plyer/blob/master/CONTACT.md)
            to get help with the project.
            
            Let us know if this comment was made in error, and we'll be happy
            to reopen the issue.
          close-issue: true
          lock-issue: false
